package com.stockbot.core.diagnostics;

public enum CauseCode {
    NONE,
    NO_BARS,
    HISTORY_SHORT,
    STALE,
    FETCH_FAILED,
    INDICATOR_ERROR,
    PLAN_INVALID,
    FEATURE_DISABLED_BY_CONFIG,
    FEATURE_NOT_IMPLEMENTED,
    FEATURE_RUNTIME_ERROR,
    TICKER_RESOLVE_FAILED,
    FILTER_REJECTED,
    RISK_REJECTED,
    SCORE_BELOW_THRESHOLD,
    GATE_SKIP_ON_PARTIAL,
    GATE_MIN_FETCH_COVERAGE,
    MISSING_INDICATORS,
    DATA_GAP,
    RUNTIME_ERROR
}
